export * from './Palette';
export * from './Plus';
export * from './Trash';
export * from './Copy';
export * from './Copied';
export * from './Pencil';
export * from './Help';
export * from './Close';
export * from './UpperArrow';
